--ORTALAMA TESLÝMAT SÜRESÝ

SELECT 
	--O.ID AS SIPARISID,
	--O.DATE_ AS SIPARISTARIHI,
	--I.DATE_ AS FATURATARIHI,
	
	MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_))	 ENUZUN_TESLIMATSURESI_SAAT,
	MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_))	 ENKISA_TESLIMATSURESI_SAAT,
	AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_))  ORTALAMA_TESLIMATSURESI_SAAT

FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID