--ÜRÜN KATEGORÝLERÝNE GÖRE   SÝPARÝÞ DAÐILIMI

SELECT 
	ITM.CATEGORY1,
	ITM.CATEGORY2,
	SUM (OD.LINETOTAL)	TOPLAMSIPARIS_TUTARI,
	SUM(OD.AMOUNT)	TOPLAMSIPARIÞ_ADEDI,
	COUNT(OD.ID)	TOPLAMSIPARIS_SAYISI,
	SUM (OD.LINETOTAL)/SUM(OD.AMOUNT)	ORTALAMABIRIMFIYAT

FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

--WHERE ITM.CATEGORY1='EV'
--WHERE ITM.CATEGORY1='KOZMETIK'

GROUP BY ITM.CATEGORY1,ITM.CATEGORY2

ORDER BY 1 DESC

SELECT * FROM ORDERS