--KULLANICI ADI AD SOYAD   ÝL ÝLÇE SEMT AÇIK ADRES
--SÝPARÝÞ ID      TARÝH   TOPLAM TUTAR     ÖDEME TARÝHÝ
--BANKA ONAY KODU     FATURA TARÝHÝ    KARGO FÝÞ NO




SELECT 
	U.USERNAME_ KULLANICIADI,
	U.NAMESURNAME ADSOYAD,
	CT.CITY IL,
	T.TOWN ILCE,
	D.DISTRICT SEMT,
	A.ADDRESSTEXT ADRES,
	O.ID SIPARISID,
	O.DATE_ TARIH,
	O.TOTALPRICE TOPLAMTUTAR,
	P.DATE_ ODEMETARIHI,
	P.APPROVECODE BANKAONAY,
	I.DATE_ FATURATARIHI,
	I.CARGOFICHENO KARGOFISNO,
	ITM.ITEMCODE URUNKODU,
	ITM.ITEMNAME URUNADI,
	OD.AMOUNT MIKTAR,
	OD.UNITPRICE BIRIMFIYAT,
	OD.LINETOTAL SATIRROPLAMI

FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

WHERE 
--U.NAMESURNAME='CEYDA GEZGÝNCÝ' AND
O.ID=26121